run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - dupl
    - goconst
    - gofmt
    - golint
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - structcheck
    - unparam
    - varcheck

linters-settings:
  dupl:
    threshold: 400
  lll:
    line-length: 170
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0.85

issues:
  exclude-rules:
    - # zipkin_proto3 package contains an underscore and we can't change it.
      path: proto/zipkin_proto3
      text: "don't use an underscore in package name"
      linters:
        - golint
