language: go
dist: trusty

services:
  - rabbitmq

matrix:
  include:
    - go: "1.14.x"
    - go: "1.15.x"
    - go: "1.16.x"
    - go: "tip"

before_install:
  - make install-tools

install:
  - go get -d -t ./...

script:
  - make test vet lint bench
  - $GOPATH/bin/goveralls -service=travis-ci

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always
