language: go
sudo: false
go:
  - 1.8.x
  - 1.9.x
  - tip
before install:
  - go get github.com/mattn/goveralls
install:
  - go get -d -t ./...
  - go get -u github.com/golang/lint/...
script:
  - make test vet lint bench
  - $GOPATH/bin/goveralls -service=travis-ci
