language: go

services:
  - rabbitmq

sudo: false

matrix:
  include:
    - go: "1.9.x"
    - go: "1.10.x"     
    - go: "1.11.x"
      env:
        - GO111MODULE=on
    - go: "1.12.x"
      env:
        - GO111MODULE=on      
    - go: "tip"
      env:
        - GO111MODULE=on

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - go get -d -t ./...
  - go get -u golang.org/x/lint/golint

script:
  - make test vet lint bench
  - $GOPATH/bin/goveralls -service=travis-ci
