version: v1.0.0.{build}

platform: x64

clone_folder: c:\gopath\src\github.com\openzipkin\zipkin-go

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GOFLAGS: -mod=readonly

install:
  - ps: Write-Host "Installing RabbitMQ..." -ForegroundColor Cyan

  - ECHO Write-Host "Downloading..."
  - ps: $exePath = "$($env:USERPROFILE)\rabbitmq-server-3.7.15.exe"
  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.15/rabbitmq-server-3.7.15.exe', $exePath)

  - ECHO Write-Host "Installing..."
  - ps: cmd /c start /wait $exePath /S

  - ps: $rabbitPath = 'C:\Program Files (x86)\RabbitMQ Server\rabbitmq-server-3.7.15'

  - ECHO Write-Host "Installing service..."
  - ps: Start-Process -Wait "$rabbitPath\sbin\rabbitmq-service.bat" "install"

  - ECHO Write-Host "Starting service..."
  - ps: Start-Process -Wait "$rabbitPath\sbin\rabbitmq-service.bat" "start"

  - ps: Get-Service "RabbitMQ"

  - ECHO Write-Host "RabbitMQ installed and started" -ForegroundColor Green

  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go vet ./...
  - go test -v -race -cover ./...
  - go test -v -run - -bench . -benchmem ./...
